- name: Install Application Packages
  when: ansible_facts['hostname'] == "webserver"
  yum:
    name: "{{app_packages}}"
    state: latest

- name: Install Remi Repositories
  when: ansible_facts['hostname'] == "webserver"
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
- name: Install yum-utils
  when: ansible_facts['hostname'] == "webserver"
  yum:
    name: yum-utils
    state: latest
- name: Enable remi-php72 repository
  when: ansible_facts['hostname'] == "webserver"
  yum_repository:
    description: Extra Packages for Enterprise Linux 7 - $basearch
    metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
    name: remi-php72
    enabled: yes

- name: Updated Repository on web-server
  when: ansible_facts['hostname'] == "webserver"
  yum:
    name: "*"
    state: latest
- name: Install PHP7.2
  when: ansible_facts['hostname'] == "webserver"
  yum:
    name: "{{php_package}}"
    state: present
    enablerepo: "remi-*,epel,base"

# - name: Download Wordpress
#   when: ansible_facts['hostname'] == "webserver" #it is going to install in webserver
#   get_url:
#     url: https://wordpress.org/latest.tar.gz
#     dest: /tmp/wordpress.tar.gz #location need to be tar.gz
#Not: Below one will do this step automaticly

- name: Download Wordpress - unarchive
  when: ansible_facts['hostname'] == "webserver"
  unarchive: 
    src: https://wordpress.org/latest.tar.gz
    dest: /tmp/
    remote_src: yes
    
- name: Copy Wordpress to /var/wwww/html
  when: ansible_facts['hostname'] == "webserver"    
  copy:
    src: /tmp/wordpress/
    dest: /var/www/html/
    remote_src: yes
    owner: apache
    group: apache
   